project:
  type: website

website:
  title: "JinYoung_Park"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



